name: 'Docker File is Getting Ready'
description: 'Docker file will be created image from podman , image will be send docker.hub repository . After image will pull machine and run.'
inputs:
  jPath:  # path
    description: ' '
    required: false
    default: ''
  jName: # Name
    description: ' '
    required: false
    default: 'devops-setting-example.json'
outputs:
  Result: 
    description: "Build step results"
    value: "Build steps  finished"
runs:
  using: "composite"
  steps: 
    - name: Repository Files are downloading
      uses: actions/checkout@v2
    
    - run : python ${{ github.action_path }}/main.py -jp ${{ inputs.jPath }} -jn ${{ inputs.jName }}
      shell: bash
   
 