name: 'Docker File is Getting Ready'
description: 'Docker file will be created image from podman , image will be send docker.hub repository . After image will pull machine and run.'
inputs:
  jPath:  # path
    description: ' '
    required: false
    default: 'default'
  jName: # Name
    description: ' '
    required: false
    default: 'devops-setting-example.json'
  Repository: # Name
    description: ' '
    required: false
    default: 'quay.io'
  RepoUserName: # Name
    description: 'Repository username'
    required: True
    default: 'username'
  RepoPassword: # Name
    description: 'Repository Password'
    required: True
    default: 'password'
outputs:
  Result: 
    description: "Build step results"
    value: "Build steps  finished"
runs:
  using: "composite"
  steps: 
    - name: Repository Files are downloading
      uses: actions/checkout@v2
    - run: echo ${{inputs.jPath}} ${{ inputs.jName }}
      shell: bash
    - run: podman login ${{inputs.Repository}} -u ${{inputs.RepoUserName}} -p ${{inputs.RepoPassword}}
      shell: bash
    - run : python ${{ github.action_path }}/main.py --jPath ${{inputs.jPath}} --jName ${{ inputs.jName }}
      shell: bash
   
 